config/routes.rb
Rails.application.routes.draw do
  resources :jobpreferences
  resources :skills
  resources :referees
  resources :experiences
  resources :educatioal_qualifications
  resources :educatioal_qualifications
  resources :people
  devise_for :users
  get 'welcome/index'
  get 'welcome/show', to: 'welcome#show'
  gem 'devise'
  gem 'twitter-bootstrap-rails'
  gem 'devise-bootstrap-views'

  root 'welcome#index'

end

app/models/person.rb
class Person < ActiveRecord::Base
  belongs_to :user
  has_many :educatioal_qualification
  has_many :skill
  has_many :experience
  has_many :referee
  has_many :jobpreferences

  accepts_nested_attributes_for :user, :educatioal_qualification, :skill, :experience, :referee, :jobpreferences

  validates :title, presence: true, length: { minimum: 1, maximum: 15 }
  validates :forename1, presence: true, length: { minimum: 1, maximum: 70 }
  validates :forename2, presence: true, length: { minimum: 1, maximum: 15 }
  validates :surname, presence: true, length: { minimum: 1, maximum: 15 }
  validates :addressLine1, presence: true, length: { minimum: 1, maximum: 75 }
  validates :addressLine2, presence: true, length: { minimum: 1, maximum: 50 }
  validates :town, presence: true, length: { minimum: 1, maximum: 50 }
  validates :postcode, presence: true, length: { minimum: 1, maximum: 15 }
  validates :secondEmail, presence: true, length: { minimum: 1, maximum: 51 }
  validates :personalUrl, presence: true, length: { minimum: 1, maximum: 50 }
  validates :female, presence: true, length: { minimum: 1, maximum: 15 }
  validates :authorityToWorkStatement, presence: true, length: { minimum: 1, maximum: 2750 }
  validates :contactPreference, presence: true, length: { minimum: 1, maximum: 15 }
  validates :noOfGcses, presence: true, length: { minimum: 1, maximum: 15 }
  validates :gecseEnglishGrade, presence: true, length: { minimum: 1, maximum: 50 }
  validates :gcseMathsGrade, presence: true, length: { minimum: 1, maximum: 15 }
  validates :fiveOrMoreGcses, presence: true, length: { minimum: 1, maximum: 15 }
  validates :noOfAlevels, presence: true, length: { minimum: 1, maximum: 15 }
  validates :ucasPoints, presence: true, length: { minimum: 1, maximum: 50 }
  validates :mobile, presence: true, length: { minimum: 1, maximum: 15 }
  validates :landline, presence: true, length: { minimum: 1, maximum: 15 }
  validates :dob, presence: true, length: { minimum: 1, maximum: 50 }
  validates :penaltyPoints, presence: true, length: { minimum: 1, maximum: 15 }
  has_attached_file :photo, styles: { thumb: ['64x64#', :jpg],
                                      original: ['300x300>', :jpg] },
                            convert_options: { thumb: '-quality 75 -strip',
                                               original: '-quality 85 -strip' }
  # validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
  validates_attachment :photo,
                       content_type: { content_type: ['image/jpeg', 'image/gif', 'image/png'] },
                       size: { in: 0..5000.kilobytes }
  has_attached_file :mycv
  validates_attachment_content_type :mycv, content_type: ['application/pdf', 'text/plain']
  before_save :user_setup

  private

  def user_setup
    self.id = user_id if id.blank?
  end

  def self.search(search_skill)
    if search_skill
      joins(:skill).where('lower(skills.skill_name) LIKE ?', "%#{search_skill.downcase}%")
    else
      find(:all)
    end
   end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  # GET /people
  # GET /people.json

  def index
    if current_user.try(:admin?)
      if params.key?(:search_edu)
       # lower(skills.skill_name) LIKE ?'
        @people = Person.all.select('*').joins(:educatioal_qualification)
                        .where('lower(educatioal_qualifications.qualification_type) LIKE ?', "%#{params[:search_edu.downcase]}%")
      elsif params.key?(:search_exp)
        @people = Person.all.select('*').joins(:experience)
                        .where('lower(experiences.other_jobtitle) LIKE ?', "%#{params[:search_exp.d]}%")
      elsif params.key?(:search_skill)

        @people = Person.select('*').search(params[:search_skill])


      else
        @people = Person.order('created_at DESC')
      end

    else
      flash[:danger] = 'You must be an admin to perform this activity'
      redirect_to root_path
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
    if current_user.try(:admin?)
      @people = Person.find(params[:id])
      @skills = Skill.all.where(user_id: params[:id])
      @experiences = Experience.all.where(user_id: params[:id])
      @educatioal_qualifications = EducatioalQualification.all.where(user_id: params[:id])
      @jobpreferences = Jobpreference.all.where(user_id: params[:id])
      @referees = Referee.all.where(user_id: params[:id])
    end
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: 'file_name',
               template: 'people/show.pdf.erb',
               layout: 'pdf.html.erb',
               show_as_html: params[:debug].present?
      end
    end
  end

  # GET /people/new
  def new
    if current_user.people.empty?
      @person = Person.new
    else
      redirect_to edit_person_path(current_user.people.first)
    end

  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)
    @person.user = current_user
    respond_to do |format|
      if @person.save
        format.html { redirect_to root_path, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to root_path, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Person was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_person
    @person = Person.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def person_params
    params.require(:person).permit(:title, :forename1, :forename2, :surname, :addressLine1, :addressLine2, :town, :postcode, :secondEmail, :personalUrl, :photo, :female, :postcodeStart, :authorityToWorkStatement, :contactPreference, :EducationalLevels_idEducatonLevel, :noOfGcses, :gecseEnglishGrade, :gcseMathsGrade, :fiveOrMoreGcses, :noOfAlevels, :ucasPoints, :studentStatus, :mobile, :landline, :dob, :penaltyPoints, :mycv)
  end

  def  require_same_user
    if current_user != @person.user
      flash[:danger] = 'You can only edit or delete your details'
      redirect_to root_path
      end
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_experience.html.erb
<% if !@people.blank? %>
<h5 align="right"> Total No of Clients <%= @people.count %> </h5>
<table class="table table-striped table-bordered table-condensed">
<thead>
  <thead>
    <tr>
      <th>Name</th>
      <th>Surname</th>
      <th>Experience As</th>
      <th>Client Uploaded CV</th>
      <th>System Generated CV</th>
      <th>Show </th>
    </tr>
  </thead>
  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td colspan="1"><%= person.forename1 %></td>
        <td colspan="1"><%= person.surname %></td>
        <td colspan="1"><%= person.other_jobtitle %></td>
        <% if !person.mycv.blank? %>
        <td colspan="1"><%= link_to "Download", person.mycv.url(:original, false) %></td>
        <% else %>
        <td colspan="1">Not Available</td>
        <% end %>
        <td colspan="1"><%= link_to 'Download', welcome_show_path(:id => person.user_id, format: 'pdf') %></td>
        <td colspan="1"><%= link_to 'Show', person_path(:id => person.user_id)%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
<h3>No record Found with Experience "<%= params[:search_exp] %>"</h3>
<% end %>
<br>
<%= link_to 'Back', root_path %>

app/views/people/_form.html.erb
<%= render 'shared/errors', obj:@person %>
<div class='row'>
  <%= form_for(@person, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="col-md-12 col-md-offset-0" >
   <div class="panel panel-default">
	  <div class="panel-heading">
     <h4 align="center"><%= t('.sign_in', :default => "Personal Deatails") %></h4>
    </div>
	<div class="panel-body">
   <div class="panel panel-info">
       <div class="panel-heading">
       <h5 align="left">My Details</h5>

    <div class="panel-body">
    <div class="row">
       <div class="col-xs-6">
        <%= f.label :Title %>
        <%= f.select :title, options_for_select([['Mr'],['Miss'],['Mrs'],['Ms']], params[:title]),{}, { class: "form-control"} %>
       </div>
      <div class="col-xs-6">
        <%= f.label :Forename %>
        <%= f.text_field :forename1 , class: "form-control" %>
      </div>
    </div>
<div class="row">
  <div class="col-xs-6">
       <%= f.label :Middle_Name,"Middle Name" %><br>
       <%= f.text_field :forename2 , class: "form-control" %>
  </div>
  <div class="col-xs-6">
      <%= f.label :Surname %><br>
      <%= f.text_field :surname , class: "form-control" %>
  </div>
</div>
<div class="row">
  <div class="col-xs-6">
     <%= f.label :Gender %><br>
     <%= f.select :female, options_for_select([['Male'],['Female']], params[:gender]),{}, { class: "form-control"} %>
  </div>
  <div class="col-xs-6">
     <%= f.label :dob,"Date of Birth" %><br>
     <%= f.date_select :dob, :start_year => Time.now.year - 14, :end_year => Time.now.year - 90, :order =>
     [:day, :month, :year], class: 'date-select' %>
  </div>
 </div>
 </div>
 </div>
</div>
   <div class="panel panel-info">
     <div class="panel-heading">
     <h5 align="left">Contact</h5>
     </div>
    <div class="panel-body">
    <div class="row">
       <div class="col-xs-6">
        <%= f.label :Address_Line1,"Address Line 1" %><br>
        <%= f.text_field :addressLine1 , class: "form-control" %>
       </div>
      <div class="col-xs-6">
        <%= f.label :Address_Line2,"Address Line 2" %><br>
        <%= f.text_field :addressLine2, class: "form-control" %>
      </div>
      </div>
<div class="row">
  <div class="col-xs-6">
       <%= f.label :Town %><br>
       <%= f.text_field :town , class: "form-control" %>
  </div>
  <div class="col-xs-6">
      <%= f.label :Postcode %><br>
      <%= f.text_field :postcode , class: "form-control" %>
  </div>
</div>
<div class="row">
  <div class="col-xs-6">
    <%= f.label :Second_Email,"Second Email" %><br>
    <%= f.text_field :secondEmail , class: "form-control" %>
  </div>
  <div class="col-xs-6">
     <%= f.label :Personal_website_Url,"Personal Website Url" %><br>
     <%= f.text_field :personalUrl , class: "form-control" %>
  </div>
 </div>
      <div class="row">
  <div class="col-xs-4">
     <%= f.label :Mobile_Number, "Mobile Number" %><br>
     <%= f.text_field :mobile , class: "form-control" %>
  </div>
  <div class="col-xs-4">
    <%= f.label :Landline_Number,"Landline Number" %><br>
    <%= f.text_field :landline , class: "form-control" %>
  </div>
  <div class="col-xs-4">
    <%= f.label :Contact_Preference,"Contact Preference" %><br>
    <%= f.select :contactPreference, options_for_select([['Mobile'],['Landline'],['Email']], params[:contactPreference]),{},
    { class: "form-control"} %>
  </div>
</div>
   <div class="row">
    <div class="col-xs-6">
    <%= f.label :Photo_Upload, "Photo Upload (Optional)" %><br>
    <%= f.file_field :photo , class: "form-control" %>
  </div>

 </div>
 </div>
 </div>

   <div class="panel panel-info">
     <div class="panel-heading">
     <h5 align="left">Basic Education </h5>
     </div>
    <div class="panel-body">
    <div class="row">
       <div class="col-xs-4">
       <%= f.label :Educational_Levels,"Education Levels" %><br>
       <%= f.select :EducationalLevels_idEducatonLevel, options_for_select([['1'],['2'],['3']],
       params[:EducationalLevels_idEducatonLevel]),{},{ class: "form-control"} %>
       <br/>
        <%= f.label :Five_Or_More_Gcses, "Five or more GCSEs" %><br>
       <%= f.select :fiveOrMoreGcses, options_for_select([['5'],['6'],['7'],['8'],['9'],['10'],['11']],
        params[:fiveOrMoreGcses]),{},{ class: "form-control"} %>
        <br/>
        <%= f.label :No_Of_A_levels, "No of 'A' Levels" %><br>

          <%= f.select :noOfAlevels, options_for_select([['1'],['2']], params[:noOfAlevels]),{},{ class: "form-control"} %>
        <br/>
       </div>
      <div class="col-xs-4">
        <%= f.label :No_Of_Gcses,"No of GCSEs" %><br>
        <%= f.select :noOfGcses, options_for_select([['1'],['2'],['3'],['4'],['5'],['6'],['7'],['8'],['9'],['10'],['11']],
        params[:noOfGcses]),{},{ class: "form-control"} %>
         <br/>
         <%= f.label :Gcse_English_Grade,"GCSE English Grade" %><br>
         <%= f.select :gecseEnglishGrade, options_for_select([['A*'],['A'],['B'],['C'],['D'],['E'],
                   ['F'],['G'],['U'],['AA*'],['AA'],['BB'],['CC'],['DD'],['EE'],
                   ['FF']], params[:gecseEnglishGrade]),{},{ class: "form-control"} %>
         <br/>
        <%= f.label :Gcse_Maths_Grade,"GCSE Maths Grade" %><br>

        <%= f.select :gcseMathsGrade, options_for_select([['A*'],['A'],['B'],['C'],['D'],['E'],
                   ['F'],['G'],['U'],['AA*'],['AA'],['BB'],['CC'],['DD'],['EE'],
                   ['FF']], params[:gcseMathsGrade]),{},{ class: "form-control"} %>
        <br/>
      </div>
       <div class="col-xs-4">
        <%= f.label :Ucas_Points, "UCAS Points" %><br>
       <%= f.select :ucasPoints, options_for_select([['20'],['30'],['40'],['50'],['60'],['70'],
                   ['80'],['90'],['100'],['110'],['120'],['140'],['150'],['160'],['170'],
                   ['180'],['190'],['200'],['210'],['220'],['230'],['240'],['250'],['260'],
                   ['270'],['280']], params[:ucasPoints]),{},{ class: "form-control"} %>
        <br/>
         <%= f.label :Student_Status, "Student Status" %><br>
         <%= f.select :studentStatus, options_for_select([['Completed'],['Current'],['Part-Time'],['Full-Time']],
       params[:studentStatus]),{},{ class: "form-control"} %>
        <br/>
        <%= f.label :Penalty_Points, "Penalty Points" %><br>
        <%= f.select :penaltyPoints, options_for_select([['0'],['1'],['2'],['3'],['4'],['5'],['6'],
                   ['7'],['8'],['9'],['10']], params[:penaltyPoints]),{},{ class: "form-control"} %>

      </div>
      </div>
   <div class="row">
    <div class="col-xs-12">
    <%= f.label :Authority_To_Work_Statement,"About Me" %><br>
    <%= f.text_area :authorityToWorkStatement , class: "form-control" %>
  </div>

 </div>
 </div>


 <div class="col-xs-12">
    <%= f.submit  class: "btn btn-primary" %>
    <br/> <br/>
    <%= link_to 'Back', root_path %>
  </div>
</div>
<% end %>
 </div>

</div>
</div>

app/views/people/_jobeducation.html.erb
<% if !@people.blank? %>
<h5 align="right"> Total No of Clients <%= @people.count %> </h5>
<table class="table table-striped table-bordered table-condensed">
<thead>
  <thead>
    <tr>
      <th>Name</th>
      <th>Surname</th>
      <th>Degree Type</th>
      <th>Client Uploaded CV</th>
      <th>System Generated CV</th>
      <th>Show </th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td colspan="1"><%= person.forename1 %></td>
        <td colspan="1"><%= person.surname %></td>
        <td colspan="1"><%= person.qualification_type %></td>
        <% if !person.mycv.blank? %>
        <td colspan="1"><%= link_to "Download", person.mycv.url(:original, false) %></td>
        <% else %>
        <td colspan="1">Not Available</td>
        <% end %>
        <td colspan="1"><%= link_to 'Download', welcome_show_path(:id => person.user_id, format: 'pdf') %></td>
        <td colspan="1"><%= link_to 'Show', person_path(:id => person.user_id)%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
<h3>No record Found with Education "<%= params[:search_edu] %>"</h3>
<% end %>
<br>
<%= link_to 'Back', root_path %>

app/views/people/_jobseeker.html.erb
<div class="page-header">
<div class="contextual">
<div class="panel panel-default">
<div class="panel-heading">Search Job Seeker <%= @people.count %></div>

 <div class="panel-body">
  <div class="row">
  <div class="col-lg-4">
    <div class="input-group">
      <%= form_tag(people_path, :method => "get") do %>
      <%= text_field_tag :search_skill, params[:search_skill], class: "form-control", placeholder: "Search by Skill" %>
      <span class="input-group-btn">
        <br/>
        <%= submit_tag "Search", class: 'btn btn-primary' %>
      </span>
      <% end %>
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->
    <div class="col-lg-4">
    <div class="input-group">
      <%= form_tag(people_path, :method => "get") do %>
      <%= text_field_tag :search_exp, params[:search_exp], class: "form-control", placeholder: "Search by Job title" %>
      <span class="input-group-btn">
        <br/>
        <%= submit_tag "Search", class: 'btn btn-primary' %>
      </span>
      <% end %>
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->
    <div class="col-lg-4">
    <div class="input-group">
      <%= form_tag(people_path, :method => "get") do %>
      <%= text_field_tag :search_edu, params[:search_edu], class: "form-control", placeholder: "Search by Degree...BSc" %>
      <span class="input-group-btn">
        <br/>
        <%= submit_tag "Search", class: 'btn btn-primary' %>
      </span>
      <% end %>
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->
</div><!-- /.row -->
<hr/>
<h5 align="right"> Total No of Clients <%= @people.count %> </h5>
<table class="table table-striped table-bordered table-condensed">
<thead>
  <thead>
    <tr>
      <th>Name</th>
      <th>Surname</th>
      <th>Town</th>
      <th>Client Uploaded CV</th>
      <th>System Generated CV</th>
      <th>Show </th>
    </tr>
  </thead>
  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td colspan="1"><%= person.forename1 %></td>
        <td colspan="1"><%= person.surname %></td>
        <td colspan="1"><%= person.town %></td>
        <% if !person.mycv.blank? %>
        <td colspan="1"><%= link_to "Download", person.mycv.url(:original, false) %></td>
        <% else %>
        <td colspan="1">Not Available</td>
        <% end %>
        <td colspan="1"><%= link_to 'Download', welcome_show_path(:id => person.id, format: 'pdf') %></td>
        <td colspan="1"><%= link_to 'Show', person_path(:id => person.id)%></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>

app/views/people/_skill.html.erb
<% if !@people.blank? %>
<h5 align="right"> Total No of Clients <%= @people.count %> </h5>
<table class="table table-striped table-bordered table-condensed">
<thead>
  <thead>
    <tr>
      <th>Name</th>
      <th>Surname</th>
      <th>Skill Name</th>
      <th>Client Uploaded CV</th>
      <th>System Generated CV</th>
      <th>Show </th>
    </tr>
  </thead>
  <tbody>

    <% @people.each do |person| %>
      <tr>
        <td colspan="1"><%= person.forename1 %></td>
        <td colspan="1"><%= person.surname %></td>
        <td colspan="1"><%= person.skill_name %></td>
        <% if !person.mycv.blank? %>
        <td colspan="1"><%= link_to "Download", person.mycv.url(:original, false) %></td>
        <% else %>
        <td colspan="1">Not Available</td>
        <% end %>
        <td colspan="1"><%= link_to 'Download', welcome_show_path(:id => person.user_id, format: 'pdf') %></td>
        <td colspan="1"><%= link_to 'Show', person_path(:id => person.user_id)%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
<h3>No record Found with Skill "<%= params[:search_skill] %>"</h3>

<% end %>
<br>
<%= link_to 'Back', root_path %>

app/views/people/index.html.erb
       <%  if params.has_key?(:search_edu) %>
       <%= render 'jobeducation', obj: @people %>
       <% elsif params.has_key?(:search_exp) %>
       <%= render 'experience', obj: @people %>
       <% elsif params.has_key?(:search_skill) %>
       <%= render 'skill', obj: @people %>
       <% end %>

app/views/people/new.html.erb
<% if current_user.people.blank? %>
  <h5 class="my-caption center">Please fill up your details to create CV</h5>
  <%= render 'form' %>
  <% else %>
  <%= render 'form' %>

<div class="form-group">
  <%= link_to 'Back', root_path %>
</div>
<% end %>

app/views/people/show.html.erb
<%= render 'welcome/cvruby', obj: @people %>

app/views/people/skill.html.erb
<div class="page-header">
<div class="contextual">

</div>
  <div class="row">
  <div class="col-lg-6">
    <div class="input-group">
      <%= form_tag(people_path, :method => "get") do %>
      <%= text_field_tag :search_skill, params[:search_skill], class: "form-control", placeholder: "Search by Skill" %>
      <span class="input-group-btn">
        <br/>
        <%= submit_tag "Search", class: 'btn btn-default' %>
      </span>
      <% end %>
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->
    <div class="col-lg-6">
    <div class="input-group">
      <%= form_tag(people_path, :method => "get") do %>
      <%= text_field_tag :search_exp, params[:search_exp], class: "form-control", placeholder: "Search by Job title" %>
      <span class="input-group-btn">
        <br/>
        <%= submit_tag "Search", class: 'btn btn-default' %>
      </span>
      <% end %>
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->
</div><!-- /.row -->
<hr/>
<table class="table table-striped table-bordered table-condensed">
<thead>
  <thead>
    <tr>
      <th>Name</th>
      <th>Surname</th>
      <th>Skill Name</th>
      <th>CV Download</th>
      <th>Show </th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td colspan="1"><%= person.forename1 %></td>
        <td colspan="1"><%= person.surname %></td>
        <td colspan="1"><%= person.skillName %></td>
        <% if !person.mycv.blank? %>
        <td colspan="1"><%= link_to "Download", person.mycv.url(:original, false) %></td>
        <% else %>
        <td colspan="1">Not Available</td>
       <% end %>
        <td colspan="1"><%= link_to 'Show', person_path(:id => person.id)%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'Back', root_path %>