config/routes.rb
Rails.application.routes.draw do
  resources :jobpreferences
  resources :skills
  resources :referees
  resources :experiences
  resources :educatioal_qualifications
  resources :educatioal_qualifications
  resources :people
  devise_for :users
  get 'welcome/index'
  get 'welcome/show', to: 'welcome#show'
  gem 'devise'
  gem 'twitter-bootstrap-rails'
  gem 'devise-bootstrap-views'

  root 'welcome#index'

end

app/models/skill.rb
class Skill < ActiveRecord::Base
  belongs_to :user
  belongs_to :person
  accepts_nested_attributes_for :user, :person

  validates :skillType, presence: true, length: { minimum: 1, maximum: 25 }
  validates :skill_name, presence: true, length: { minimum: 1, maximum: 25 }
  #validates :skill_name, uniqueness: { case_sensitive: false }
  #validates_uniqueness_of :skill_name, scope: :user_id
  validates :skillLevel, presence: true, length: { minimum: 1, maximum: 75 }

  before_save :user_setup


  private

  def user_setup
    self.person_id = user_id
  end


end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  # GET /skills
  # GET /skills.json
  def index
    if current_user.try(:admin?)
      @skills = if params[:search]
                  Skill.all.order('created_at DESC')
                else
                  current_user.skills.order('skillType ASC')
                end
    else
      flash[:danger] = 'You must be an admin to perform this activity'
      redirect_to root_path
      end
  end

  # GET /skills/1
  # GET /skills/1.json
  def show
  end

  # GET /skills/new
  def new
    if current_user.skills.count < 11
      @skill = Skill.new
    else
      redirect_to edit_skill_path(current_user.skills.first)
    end
  end

  # GET /skills/1/edit
  def edit
  end
  def message
    flash.now[:notice] = "#{@skill.skillName} is in use as an ingredient and cannot be deleted"
  end
  # POST /skills
  # POST /skills.json
  def create
    @skill = Skill.new(skill_params)
    @skill.user = current_user
    respond_to do |format|
      if @skill.save
        format.html { redirect_to root_path, notice: 'Skill was successfully created.' }
        format.json { render :show, status: :created, location: @skill }
      else
        format.html { render :new }
        format.json { render json: @skill.errors, status: :unprocessable_entity }

      end
    end
  end

  # PATCH/PUT /skills/1
  # PATCH/PUT /skills/1.json
  def update
    respond_to do |format|
      if @skill.update(skill_params)
        format.html { redirect_to root_path, notice: 'Skill was successfully updated.' }
        format.json { render :show, status: :ok, location: @skill }
      else
        format.html { render :edit }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skills/1
  # DELETE /skills/1.json
  def destroy
    @skill.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Skill was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_skill
    @skill = Skill.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def skill_params
    params.require(:skill).permit(:idSkills, :skillType, :Person_idUser, :skill_name, :skillLevel, :verified, :howVerified)
  end

  def require_same_user
    if current_user != @skill.user
      flash[:danger] = 'You can only edit or delete your details'
      redirect_to root_path
       end
  end
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/skills/_form.html.erb
<%= render 'shared/errors', obj:@skill %>
<div class='row'>
  <%= form_for(@skill, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="col-md-12 col-md-offset-0" >
   <div class="panel panel-default">
	  <div class="panel-heading">
     <h4 align="center"><%= t('.sign_in', :default => "Skills") %></h4>
	<div class="panel-body">
    <div class="form-group">
    <%= f.label :Skill_Type,"Skill Type" %><br>
    <%= f.text_field :skillType,:placeholder => "Programming.....", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :skill_name,"Skill Name" %><br>
    <%= f.text_field :skill_name, :placeholder => "Java, Ruby.....", class: "form-control" %>
  </div>
 <div class="form-group">
    <%= f.label :Skill_Level, "Skill Level" %><br>
    <%= f.select :skillLevel, options_for_select([['1'],['2'],['3'],['4'],['5'],['6'],['7'],['8'],['9'],['10']], params[:title]),{}, { class: "form-control"} %>
  </div>
  <div class="actions form-group">
    <%= f.submit "Submit" , class: "btn btn-primary" %>
  </div>
<% end %>

app/views/skills/edit.html.erb
<h1>Editing Skill</h1>

<%= render 'form' %>

 <div class="form-group">
   <%= link_to 'Back', skills_path %>
</div>

app/views/skills/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Skills</h1>

<table>
  <thead>
    <tr>
      <th>Skillname</th>
      <th>Skilllevel</th>
      <th>Verified</th>
      <th>Howverified</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @skills.each do |skill| %>
      <tr>
        <td><%= skill.skill_name %></td>
        <td><%= skill.skillLevel %></td>
        <td><%= skill.verified %></td>
        <td><%= skill.howVerified %></td>
        <td><%= link_to 'Show', skill %></td>
        <td><%= link_to 'Edit', edit_skill_path(skill) %></td>
        <td><%= link_to 'Destroy', skill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Skill', new_skill_path %>

app/views/skills/new.html.erb
<h3>New Skill </h3>

<%= render 'form' %>

 <div class="form-group">
 <%= link_to 'Back', root_path %>
</div>

app/views/skills/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Skillname:</strong>
  <%= @skill.skillName %>
</p>

<p>
  <strong>Skilllevel:</strong>
  <%= @skill.skillLevel %>
</p>

<p>
  <strong>Verified:</strong>
  <%= @skill.verified %>
</p>

<p>
  <strong>Howverified:</strong>
  <%= @skill.howVerified %>
</p>

<%= link_to 'Edit', edit_skill_path(@skill) %> |
<%= link_to 'Back', skills_path %>