config/routes.rb
Rails.application.routes.draw do
  resources :jobpreferences
  resources :skills
  resources :referees
  resources :experiences
  resources :educatioal_qualifications
  resources :educatioal_qualifications
  resources :people
  devise_for :users
  get 'welcome/index'
  get 'welcome/show', to: 'welcome#show'
  gem 'devise'
  gem 'twitter-bootstrap-rails'
  gem 'devise-bootstrap-views'

  root 'welcome#index'

end

app/models/educatioal_qualification.rb
class EducatioalQualification < ActiveRecord::Base
  belongs_to :user
  belongs_to :educatioal_qualification
  accepts_nested_attributes_for :user, :educatioal_qualification
  validates :qualification_type, presence: true, length: { minimum: 1, maximum: 15 }
  validates :courseName, presence: true, length: { minimum: 1, maximum: 70 }
  #validates :courseName, uniqueness: { case_sensitive: false }
  #validates_uniqueness_of :courseName, scope: :user_id
  validates :EducationalLevels_idEducationLevel, presence: true, length: { minimum: 1, maximum: 15 }
  validates :nameOfInstitutions, presence: true, length: { minimum: 1, maximum: 75 }
  validates :mainSubject, presence: true, length: { minimum: 1, maximum: 50 }
  validates :country, presence: true, length: { minimum: 1, maximum: 50 }
  validates :yearObtained, presence: true, length: { minimum: 1, maximum: 15 }
  validates :result, presence: true, length: { minimum: 1, maximum: 45 }
  validates :thesesTitle, presence: true, length: { minimum: 1, maximum: 50 }
  before_save :user_setup

  private

  def user_setup
    self.person_id = user_id
  end
end

app/controllers/educatioal_qualifications_controller.rb
class EducatioalQualificationsController < ApplicationController
  before_action :set_educatioal_qualification, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  # GET /educatioal_qualifications
  # GET /educatioal_qualifications.json

  def index
    if current_user.try(:admin?)
      @educatioal_qualifications = EducatioalQualification.all
    else
      flash[:danger] = 'You must be an admin to perform this activity'
      redirect_to root_path
    end
   end

  # GET /educatioal_qualifications/1
  # GET /educatioal_qualifications/1.json
  def show
  end

  # GET /educatioal_qualifications/new
  def new
    if current_user.educatioal_qualifications.count < 5
      @educatioal_qualification = EducatioalQualification.new
    else
      flash[:danger] = 'You can add only five Education Details'
      redirect_to edit_educatioal_qualification_path(current_user.educatioal_qualifications.first)
     end
  end

  # GET /educatioal_qualifications/1/edit
  def edit
  end

  # POST /educatioal_qualifications
  # POST /educatioal_qualifications.json
  def create
    @educatioal_qualification = EducatioalQualification.new(educatioal_qualification_params)
    @educatioal_qualification.user = current_user
    respond_to do |format|
      if @educatioal_qualification.save
        format.html { redirect_to root_path, notice: 'Educatioal qualification was successfully created.' }
        format.json { render :show, status: :created, location: @educatioal_qualification }
      else
        format.html { render :new }
        format.json { render json: @educatioal_qualification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /educatioal_qualifications/1
  # PATCH/PUT /educatioal_qualifications/1.json
  def update
    respond_to do |format|
      if @educatioal_qualification.update(educatioal_qualification_params)
        format.html { redirect_to root_path, notice: 'Educatioal qualification was successfully updated.' }
        format.json { render :show, status: :ok, location: @educatioal_qualification }
      else
        format.html { render :edit }
        format.json { render json: @educatioal_qualification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /educatioal_qualifications/1
  # DELETE /educatioal_qualifications/1.json
  def destroy
    @educatioal_qualification.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Educatioal qualification was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_educatioal_qualification
    @educatioal_qualification = EducatioalQualification.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def educatioal_qualification_params
    params.require(:educatioal_qualification).permit(:idEducationalQualification, :Persons_idUser, :qualification_type, :courseName, :EducationalLevels_idEducationLevel, :vocational, :mainSubject, :nameOfInstitutions, :country, :yearObtained, :result, :thesesTitle, :verified, :howVerified)
  end

  def require_same_user
    if current_user != @educatioal_qualification.user
      flash[:danger] = 'You can only edit or delete your details'
      redirect_to root_path
      end
   end
end

app/helpers/educatioal_qualifications_helper.rb
module EducatioalQualificationsHelper
end

app/views/educatioal_qualifications/_form.html.erb
<%= render 'shared/errors', obj:@educatioal_qualification %>
<div class='row'>
  <%= form_for(@educatioal_qualification, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="col-md-12 col-md-offset-0" >
   <div class="panel panel-default">
	  <div class="panel-heading">
     <h4 align="center"><%= t('.sign_in', :default => "Educational Deatails") %></h4>

	<div class="panel-body">
    <div class="form-group">
    <%= f.label :qualification_type,"Qualification Type"%><br>
    <%= f.text_field :qualification_type,:placeholder => "Bachelor/Master/PhD", class: "form-control" %>
  </div>
    <div class="form-group">
    <%= f.label :courseName, "Course Name" %><br>
    <%= f.text_field :courseName,:placeholder => "Computer Science", class: "form-control" %>
  </div>
   <div class="form-group">
    <%= f.label :EducationalLevels_idEducationLevel,"Education Level" %><br>
     <%= f.select :EducationalLevels_idEducationLevel, options_for_select([['1'],['2'],['3'],['4'],['5'],['6'],['7'],['8']],
       params[:title]),{}, { class: "form-control"} %>
     </div>

    <div class="form-group">
    <%= f.label :mainSubject,"Main Subject" %><br>
    <%= f.text_field :mainSubject,:placeholder => "Software Development", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :nameOfInstitutions, "Name of Institutions" %><br>
    <%= f.text_field :nameOfInstitutions,:placeholder => "University of Ulster", class: "form-control" %>
  </div>
    <div class="form-group">
    <%= f.label :country, "Country" %><br>
    <%= f.country_select(:country, { priority_countries: ["GB", "IN", "US"], selected: "GB" },
    { class: 'form-control', data: { attribute: "value" } }) %>
  </div>
  <div class="form-group">
    <%= f.label :yearObtained, "Year of Obtained or Expected "%><br>
    <%= f.date_select :yearObtained, :start_year => Time.now.year + 3, :end_year => Time.now.year - 90, :order =>
     [:month, :year], class: 'date-select' %>


  </div>
   <div class="form-group">
    <%= f.label :result, "Result" %><br>
    <%= f.select :result, options_for_select([['First class 1'],['Second class (2.1)'],
        ['Second class (2.2)'],['Third class(3)'],['Pass'],
        ['Merit'],['Distinction']], params[:result]),{}, { class: "form-control"} %>
  </div>
   <div class="form-group">
    <%= f.label :thesesTitle,"Thesis Title" %><br>
    <%= f.text_field :thesesTitle,:placeholder => "Project Name or Theese Title", class: "form-control" %>
  </div>

  <div class="actions form-group">
    <%= f.submit "Submit" , class: "btn btn-primary" %>
  </div>
<% end %>

app/views/educatioal_qualifications/edit.html.erb
<%= render 'form' %>

 <div class="form-group">
  <%= link_to 'Back', educatioal_qualifications_path %>
 </div>

app/views/educatioal_qualifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Educatioal Qualifications</h1>

<table>
  <thead>
    <tr>
      <th>Qualificationtype</th>
      <th>Coursename</th>
      <th>Educationallevels ideducationlevel</th>
      <th>Vocational</th>
      <th>Mainsubject</th>
      <th>Nameofinstitutions</th>
      <th>Country</th>
      <th>Yearobtained</th>
      <th>Result</th>
      <th>Thesestitle</th>
      <th>Verified</th>
      <th>Howverified</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @educatioal_qualifications.each do |educatioal_qualification| %>
      <tr>
        <td><%= educatioal_qualification.qualificationType %></td>
        <td><%= educatioal_qualification.courseName %></td>
        <td><%= educatioal_qualification.EducationalLevels_idEducationLevel %></td>
        <td><%= educatioal_qualification.vocational %></td>
        <td><%= educatioal_qualification.mainSubject %></td>
        <td><%= educatioal_qualification.nameOfInstitutions %></td>
        <td><%= educatioal_qualification.country %></td>
        <td><%= educatioal_qualification.yearObtained %></td>
        <td><%= educatioal_qualification.result %></td>
        <td><%= educatioal_qualification.thesesTitle %></td>
        <td><%= educatioal_qualification.verified %></td>
        <td><%= educatioal_qualification.howVerified %></td>
        <td><%= link_to 'Show', educatioal_qualification %></td>
        <td><%= link_to 'Edit', edit_educatioal_qualification_path(educatioal_qualification) %></td>
        <td><%= link_to 'Destroy', educatioal_qualification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Educatioal qualification', new_educatioal_qualification_path %>

app/views/educatioal_qualifications/new.html.erb
<h3>New Educational Qualification</h3>

<%= render 'form' %>
 <div class="form-group">
  <%= link_to 'Back', root_path %>
  </div>

app/views/educatioal_qualifications/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Qualificationtype:</strong>
  <%= @educatioal_qualification.qualificationType %>
</p>

<p>
  <strong>Coursename:</strong>
  <%= @educatioal_qualification.courseName %>
</p>

<p>
  <strong>Educationallevels ideducationlevel:</strong>
  <%= @educatioal_qualification.EducationalLevels_idEducationLevel %>
</p>

<p>
  <strong>Vocational:</strong>
  <%= @educatioal_qualification.vocational %>
</p>

<p>
  <strong>Mainsubject:</strong>
  <%= @educatioal_qualification.mainSubject %>
</p>

<p>
  <strong>Nameofinstitutions:</strong>
  <%= @educatioal_qualification.nameOfInstitutions %>
</p>

<p>
  <strong>Country:</strong>
  <%= @educatioal_qualification.country %>
</p>

<p>
  <strong>Yearobtained:</strong>
  <%= @educatioal_qualification.yearObtained %>
</p>

<p>
  <strong>Result:</strong>
  <%= @educatioal_qualification.result %>
</p>

<p>
  <strong>Thesestitle:</strong>
  <%= @educatioal_qualification.thesesTitle %>
</p>

<p>
  <strong>Verified:</strong>
  <%= @educatioal_qualification.verified %>
</p>

<p>
  <strong>Howverified:</strong>
  <%= @educatioal_qualification.howVerified %>
</p>

<%= link_to 'Edit', edit_educatioal_qualification_path(@educatioal_qualification) %> |
<%= link_to 'Back', root_path %>