config/routes.rb
Rails.application.routes.draw do
  resources :jobpreferences
  resources :skills
  resources :referees
  resources :experiences
  resources :educatioal_qualifications
  resources :educatioal_qualifications
  resources :people
  devise_for :users
  get 'welcome/index'
  get 'welcome/show', to: 'welcome#show'
  gem 'devise'
  gem 'twitter-bootstrap-rails'
  gem 'devise-bootstrap-views'

  root 'welcome#index'

end

app/views/layouts/_messages.html.erb
<div class="row">
<div class="col-xs-10 col-xs-offset-1">
<% flash.each do |name, msg| %>
<div class='alert alert-<%="#{name}" %>'>
<a href="#" class="close" data-dismiss="alert">×</a>
<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
</div>
<% end %>
</div>
</div>

app/views/layouts/_navigation.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Ruby CV Builder" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>


    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">

        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Ruby CV Builder", root_path, class: "navbar-brand", id: "logo" %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
						<% if logged_in? and not current_user.try(:admin?) %>
						<% if current_user %>
            <li><%= link_to 'Personal', new_person_path %></li>
						<li><%= link_to "Educational", new_educatioal_qualification_path %></li>
						<li><%= link_to "Experience", new_experience_path %></li>
						<li><%= link_to "Job Preferences", new_jobpreference_path %></li>
						<li><%= link_to "Skills", new_skill_path %></li>
            <li><%= link_to "Referee", new_referee_path %></li>

					  <li><%= link_to('Logout', destroy_user_session_path,
					  class: 'btn-xs btn-danger', title: 'Logout', :method => :delete) %><li>
            <% end %>
						<% elsif current_user.try(:admin?) %>
            <li><%= link_to 'Job Seeker', root_path %></li>
            <% end %>
          </ul>
					<ul class="nav navbar-right col-md-4">
					<% if current_user.try(:admin?) %>
					<li class="col-md-8 user-name">
            <%= link_to ('<i class="fa  fa-user-secret"></i> ' + truncate(current_user.email, length: 45)).html_safe,
					edit_user_registration_path, title: 'Edit Profile' %>
				 <h6 align="left|justify"style="color:white">Logged in as Admin</h6>
				 <h6 align="left|justify"style="color:white"> Last Logged in <%= current_user.last_sign_in_at.strftime("%d %b %Y %H:%M:%S") %></h6>
				 <h6 align="left|justify"style="color:white">Logged in <%= current_user.sign_in_count %> times </h6>
					</li>
					<li class="col-md-1"> </li>
					<li class="col-md-3 logout"><%= link_to('Logout', destroy_user_session_path,
					class: 'btn btn-xs btn-danger', title: 'Logout', :method => :delete) %>
					<% elsif current_user %>
            <%= link_to ('<i class="fa fa-user"></i> ' + truncate(current_user.email, length: 45)).html_safe,
					edit_user_registration_path, title: 'Edit Profile' %>
					<h6 align="left|justify"style="color:white"><%= @username %></h6>
				  <h6 align="left|justify"style="color:white"> Last Logged in: <%= current_user.last_sign_in_at.strftime("%d %b %Y %H:%M:%S") %></h6>
				  <h6 align="left|justify"style="color:white">Logged in: <%= current_user.sign_in_count %> times </h6>
					</li>
					<li class="col-md-1"> </li>


					<% else %>
					<li class="col-md-4 pull-right">
					<%= link_to('Sign In', new_user_session_path, class: 'btn btn-primary', title: 'Sign In') %>
					</li>
					<% end %>
					</ul>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2" >
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
       </div><!--/row-->
      </div> <!-- /container -->
		 <div class="footer navbar-fixed-bottom secondary">
     <p align="center" style="color:white;"> MSc Software Engineering Kingston University Software Quality Engineering &copy; Viralkumar Patel and Joakim 2016</p>
    </div>
  </body>

</html>

app/views/layouts/application.html.erb
<%= render 'layouts/navigation' %>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> <%=@people.forename1%>.pdf</title>
  <%= wicked_pdf_stylesheet_link_tag 'application', media: 'all' %>

</head>
<body>
  <div class='container'>
    <%= yield %>
  </div>

</body>
</html>